language: rust

matrix:
  include:
    - env: TARGET=thumbv7m-none-eabi
      rust: stable
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi
      if: (type = pull_request AND branch = master)

    - env: TARGET=thumbv7m-none-eabi
      rust: beta
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi
      if: (type = pull_request AND branch = master)

    - env: TARGET=thumbv7m-none-eabi
      rust: nightly
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi
      if: (type = pull_request AND branch = master)

before_install: set -e

install:
  - bash ci/install.sh

script:
  - cargo check --target $TARGET
  - cargo build --verbose --all
  - cargo test --verbose --all

after_script: set +e

cache: cargo

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  - chmod -R a+r $TRAVIS_HOME/.cargo;

branches:
  only:
    - master

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email:
    on_success: never
